# Generated by Django 3.2.25 on 2025-10-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_change_arrears_history_to_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('allow_new_registrations', models.BooleanField(default=True, help_text='Allow new user registrations')),
                ('default_user_role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', help_text='Default role for new users', max_length=20)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='YearManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Passout year', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this year is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Year Management',
                'verbose_name_plural': 'Year Management',
                'ordering': ['-year'],
            },
        ),
    ]
