# Generated by Django 5.2 on 2025-05-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applied_data_snapshot',
            field=models.JSONField(null=True),
        ),
    ]
