# Generated by Django 5.2 on 2025-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_applied_data_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='on_campus',
            field=models.BooleanField(default=True),
        ),
    ]
