# Generated by Django 5.1.5 on 2025-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_companyform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyform',
            name='key',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
