# Generated by Django 5.1.6 on 2025-06-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_companyform_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
