# Generated by Django 5.1.6 on 2025-06-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_add_status_to_companyform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyform',
            name='status',
        ),
    ]
