# Generated by Django 3.2.25 on 2025-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_merge_20250702_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='additional_fields',
            field=models.JSONField(blank=True, default=list, help_text='Custom fields for job application form'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interview_rounds',
            field=models.JSONField(blank=True, default=list, help_text='List of interview rounds with name, date, and time'),
        ),
    ]
