# Generated by Django 5.1.5 on 2025-10-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_companyform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='allowed_passout_years',
            field=models.JSONField(blank=True, default=list, help_text='List of passout years that can view and apply for this job. Empty list means all students can view.'),
        ),
    ]
