# Generated by Django 5.1.5 on 2025-10-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobposting_allowed_passout_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='allowed_departments',
            field=models.JSONField(blank=True, default=list, help_text='List of departments that can view and apply for this job. Empty list means all students can view.'),
        ),
    ]
