# Generated by Django 5.1.5 on 2025-10-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_jobposting_allowed_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='arrears_requirement',
            field=models.CharField(choices=[('NO_RESTRICTION', 'No restriction on arrears'), ('ALLOW_WITH_ARREARS', 'Allow students with active arrears'), ('NO_ARREARS_ALLOWED', 'Students must have no active arrears')], default='NO_RESTRICTION', help_text='Arrears requirement for applicants', max_length=20),
        ),
    ]
