# Generated by Django 3.2.25 on 2025-10-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_jobposting_arrears_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='arrears_requirement',
            field=models.CharField(choices=[('NO_RESTRICTION', 'No restriction on arrears'), ('NO_ARREARS', 'No arrears allowed'), ('MAX_ONE_ARREAR', 'Maximum 1 arrear allowed'), ('MAX_TWO_ARREARS', 'Maximum 2 arrears allowed')], default='NO_RESTRICTION', help_text='Arrears requirement for applicants', max_length=20),
        ),
    ]
