# Generated by Django 5.1.5 on 2025-10-21 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alter_jobposting_arrears_requirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_in_stage', models.IntegerField(default=0, help_text='Order within stage column')),
                ('rating', models.IntegerField(choices=[(0, 'Not Rated'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags like 'Roaster', etc.")),
                ('notes', models.TextField(blank=True, help_text='Internal notes about candidate', null=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, help_text='How they found the job', max_length=100, null=True)),
                ('medium', models.CharField(blank=True, help_text='Application medium', max_length=100, null=True)),
                ('referred_by', models.CharField(blank=True, help_text='Referrer name', max_length=200, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposed_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extra_advantages', models.TextField(blank=True, null=True)),
                ('availability_status', models.CharField(default='Directly Available', help_text='e.g., Directly Available, 2 weeks notice, etc.', max_length=50)),
                ('moved_to_current_stage_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_card', to='jobs.jobapplication')),
                ('interviewers', models.ManyToManyField(blank=True, related_name='interviews', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruited_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['current_stage__order_index', 'position_in_stage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal comment vs candidate-visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_comments', to=settings.AUTH_USER_MODEL)),
                ('candidate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.candidatecard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stage_type', models.CharField(choices=[('NEW', 'New Applications'), ('SCREENING', 'Initial Screening'), ('FIRST_INTERVIEW', 'First Interview'), ('SECOND_INTERVIEW', 'Second Interview'), ('TECHNICAL', 'Technical Round'), ('HR_ROUND', 'HR Round'), ('CONTRACT_PROPOSAL', 'Contract Proposal'), ('CONTRACT_SIGNED', 'Contract Signed'), ('OFFER_MADE', 'Offer Made'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('CUSTOM', 'Custom Stage')], default='CUSTOM', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0, help_text='Display order in pipeline')),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for UI', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_terminal', models.BooleanField(default=False, help_text='Whether this is a final stage (accepted/rejected)')),
                ('organization_name', models.CharField(default='Caffeine Junction - Coffeeland', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
                'indexes': [models.Index(fields=['organization_name', 'is_active'], name='jobs_pipeli_organiz_a03b89_idx'), models.Index(fields=['order_index'], name='jobs_pipeli_order_i_3bc442_idx')],
            },
        ),
        migrations.AddField(
            model_name='candidatecard',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='jobs.pipelinestage'),
        ),
        migrations.CreateModel(
            name='RecruitmentPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization_name', models.CharField(default='Caffeine Junction - Coffeeland', max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Default pipeline for all jobs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pipelines', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text='If set, pipeline is specific to this job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='jobs.jobposting')),
                ('stages', models.ManyToManyField(blank=True, related_name='pipelines', to='jobs.pipelinestage')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidatecard',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_cards', to='jobs.recruitmentpipeline'),
        ),
        migrations.CreateModel(
            name='ShareableLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('applications_view', models.BooleanField(default=False, help_text='Link to applications view instead of specific pipeline')),
                ('permission_level', models.CharField(choices=[('VIEW', 'View Only'), ('COMMENT', 'View and Comment'), ('EDIT', 'View, Comment, and Move Cards'), ('FULL', 'Full Access')], default='VIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date', null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shareable_links', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareable_links', to='jobs.recruitmentpipeline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageMovementHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('duration_in_previous_stage', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('candidate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_movements', to='jobs.candidatecard')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='jobs.pipelinestage')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_movements_made', to=settings.AUTH_USER_MODEL)),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='jobs.pipelinestage')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recruitmentpipeline',
            index=models.Index(fields=['organization_name', 'is_active'], name='jobs_recrui_organiz_c67eac_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatecard',
            index=models.Index(fields=['pipeline', 'current_stage'], name='jobs_candid_pipelin_4d0ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatecard',
            index=models.Index(fields=['current_stage', 'position_in_stage'], name='jobs_candid_current_b86250_idx'),
        ),
        migrations.AddIndex(
            model_name='shareablelink',
            index=models.Index(fields=['token', 'is_active'], name='jobs_sharea_token_4b3c68_idx'),
        ),
        migrations.AddIndex(
            model_name='stagemovementhistory',
            index=models.Index(fields=['candidate_card', '-moved_at'], name='jobs_stagem_candida_131b60_idx'),
        ),
    ]
