# Generated by Django 3.2.25 on 2025-10-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_candidatecard_candidatecomment_pipelinestage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='min_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum CGPA required for applicants. Leave blank for no CGPA requirement.', max_digits=4, null=True),
        ),
    ]
