# Generated by Django 5.1.5 on 2025-07-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_performance_indexes'),
        ('companies', '0003_companyfollower'),
    ]

    operations = [
    ]
