# Generated by Django 3.2.25 on 2025-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge_20250702_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='min_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum CGPA required for applicants. Leave blank for no CGPA requirement.', max_digits=4, null=True),
        ),
    ]
