# Generated by Django 3.2.25 on 2025-10-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_min_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='min_cgpa',
        ),
    ]
