# Generated by Django 5.1.6 on 2025-06-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='employee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
