# Generated by Django 5.1.6 on 2025-06-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employerprofile_company_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
    ]
