# Generated by Django 5.1.5 on 2025-06-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_employer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='joining_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passout_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
