# Generated by Django 5.1.5 on 2025-07-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentprofile_semester1_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='tenth_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tenth_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='twelfth_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
