# Generated by Django 5.1.5 on 2025-07-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_performance_indexes'),
        ('accounts', '0012_studentprofile_tenth_location_and_more'),
    ]

    operations = [
    ]
