# Generated by Django 5.1.5 on 2025-10-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_update_file_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='arrears',
            field=models.PositiveIntegerField(default=0, help_text='Number of academic arrears'),
        ),
    ]
