# Generated by Django 5.1.5 on 2025-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_studentprofile_arrears'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='active_arrears',
            field=models.PositiveIntegerField(default=0, help_text='Number of currently active arrears'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='arrears_history',
            field=models.JSONField(blank=True, default=list, help_text='Historical arrears data'),
        ),
    ]
