# Generated by Django 5.1.5 on 2025-10-02 18:05

from django.db import migrations, models


def convert_arrears_history_to_count(apps, schema_editor):
    """Convert arrears_history from list to integer count"""
    StudentProfile = apps.get_model('accounts', 'StudentProfile')
    
    for profile in StudentProfile.objects.all():
        if isinstance(profile.arrears_history, list):
            # Convert list length to integer
            profile.arrears_history = len(profile.arrears_history)
            profile.save(update_fields=['arrears_history'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_studentprofile_active_arrears_and_more'),
    ]

    operations = [
        migrations.RunPython(
            convert_arrears_history_to_count,
            reverse_code=migrations.RunPython.noop  # No reverse migration needed
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='arrears_history',
            field=models.PositiveIntegerField(default=0, help_text='Number of historical arrears cleared'),
        ),
    ]
