# Generated by Django 3.2.25 on 2025-10-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_systemsettings_yearmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='placed_job_id',
            field=models.CharField(blank=True, help_text='Job ID of the job the student was placed in', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='placement_status',
            field=models.CharField(choices=[('not_placed', 'Not Placed'), ('placed', 'Placed')], default='not_placed', help_text='Current placement status of the student', max_length=20),
        ),
    ]
