# Generated by Django 3.2.25 on 2025-10-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_college_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(help_text='Branch/Department name', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this branch is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch Management',
                'verbose_name_plural': 'Branch Management',
                'ordering': ['branch'],
            },
        ),
    ]
