# Generated by Django 5.1.6 on 2025-06-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_jobposting_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
