# Generated by Django 5.1.5 on 2025-07-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_performance_indexes'),
        ('jobs', '0011_add_is_published_field'),
    ]

    operations = [
    ]
