# Generated by Django 5.1.5 on 2025-09-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_enhance_job_application_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
