# Generated by Django 3.2.25 on 2025-10-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_jobposting_arrears_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='arrears_requirement',
            field=models.CharField(choices=[('NO_RESTRICTION', 'No restriction on arrears'), ('ALLOW_WITH_ARREARS', 'Allow students with active arrears'), ('NO_ARREARS_ALLOWED', 'Students must have no active arrears')], default='NO_RESTRICTION', help_text='Arrears requirement for applicants', max_length=20),
        ),
    ]
